### PR TITLE
Update config.mk

### PR DESCRIPTION
**Pull request by DmitryHetman**

### CODE REVIEW

**Comment by michaelforney** [comment]
Why? The point of `config.mk` is that you edit it (or provide your own version) with the flags you want.

**Comment by michaelforney** [comment]
Why? The point of `config.mk` is that you edit it (or provide your own version) with the flags you want.

**Comment by DmitriyHetman** [comment]
musl library doesn't have <error.h>, it have <err.h>

**Comment by DmitriyHetman** [comment]
GCC and Clang support this optimizations

**Comment by michaelforney** [comment]
Sure, there are many optimization flags you can pass to gcc and clang. But why should swc choose those flags for you?

If you want to build with `-O2 -march=native`, then put that into your `config.mk` before building.

**Comment by DmitriyHetman** [comment]
Ok -march=native is not good for creating .deb .rpm .pac packages for different PC, but -02 should be default.

**Comment by pickfire** [comment]
Shouldn't swc recognise `CFLAGS`? Like it can use `CFLAGS ?=` or `CFLAGS +=`?

**Comment by michaelforney** [comment]
pickfire: I removed `CFLAGS` from the default `config.mk` to address your concern.

**Pull request closed without merging**
